name: KiCad DRC

on:
  push:
    branches:
      - main
    paths:
      - echo-esphome.kicad_pcb  # Trigger only if echo-esphome.kicad_pcb is changed

  pull_request:
    branches:
      - main
    paths:
    - echo-esphome.kicad_pcb  # Trigger only if echo-esphome.kicad_pcb is changed

jobs:
  drc-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install numpy
        pip install Pillow
        pip install matplotlib
        pip install scipy

    - name: Install KiCad CLI and librsvg tools
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update && sudo apt-get install --install-recommends -y kicad librsvg2-bin

    - name: Generate DRC report
      run: |
        kicad-cli pcb drc echo-esphome.kicad_pcb --format json --output /tmp/pcb-drc-report.json

    - name: Run DRC analysis script
      run: |
        python .github/scripts/analyze_kicad_drc.py /tmp/pcb-drc-report.json
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Create DRC analysis heatmap
      if: failure()
      run: |
        kicad-cli pcb export svg -l "B.Cu,F.Cu,B.Silkscreen,F.Silkscreen,Edge.Cuts,B.Mask,F.Mask" --black-and-white -o /tmp/pcb.svg echo-esphome.kicad_pcb
        rsvg-convert -b white -w 3508 -h 2480 /tmp/pcb.svg -o /tmp/pcb.png
        python .github/scripts/overlay_heatmap.py /tmp/pcb-drc-report.json /tmp/pcb.png /tmp/pcb-drc-heatmap.png

    - name: Archive PCB DRC report and heatmap
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: drc
        path: |
          /tmp/pcb-drc-report.json
          /tmp/pcb-drc-heatmap.png
